CREATE TYPE "CheckoutSessionStatus" AS ENUM ('LOCKED', 'EXPIRED', 'ABANDONED');
CREATE TYPE "CheckoutLockReleaseReason" AS ENUM ('EXPIRED', 'TRADER_ABANDONED', 'OPPORTUNITY_CANCELLED', 'ADMIN_ABANDONED');
CREATE TYPE "ShippingTierCode" AS ENUM ('SAME_CITY', 'SAME_REGION_DIFFERENT_CITY', 'DIFFERENT_REGION');
